version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Use cloud Neo4j Aura instance
      - NEO4J_URI=neo4j+s://9ade235d.databases.neo4j.io
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=f1WMma2rOlQHPLCktIfb0mbXJMGs_6M87_1jMsQF49E
      - PORT=8080
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./frontend:/app/frontend
      - ./.env:/app/.env
    # Override for development: run as root with reload
    user: root
    command: sh -c "uvicorn backend.api.main:app --host 0.0.0.0 --port \${PORT:-8080} --reload"
